version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5

executors:
  yamp-docker-img:
    docker:
      - image: banucalin/yamp:latest

jobs:
  test-check-profile:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate cargo dependencies
          command: cargo generate-lockfile
      - restore_cache:
          key: cargo-registry-key-{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
      - restore_cache:
          key: cargo-audit-key-{{ .Environment.AUDIT_CACHE_VERSION }}
      - run:
          name: Fetch cargo dependencies
          command: cargo fetch
      - run:
          name: Generate unit test xml
          command: cargo +nightly test -- -Z unstable-options --format json --report-time | cargo2junit > unit_test_results.xml
      - run:
          name: Generate profile data
          command: ./profile.sh --test --clean --tool grcov --format lcov --output profile-data
      - run:
          name: Check formatting
          command: cargo clean && cargo fmt --all -- --check
      - run:
          name: Check linting
          command: cargo clean && cargo clippy --no-deps
      - run:
          name: Check for known security issues in dependencies
          command: cargo clean && cargo audit || true
      - save_cache:
          paths: /usr/local/cargo/registry
          key: cargo-registry-key-{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
      - save_cache:
          paths: /usr/local/cargo/advisory-db
          key: cargo-audit-key-{{ .Environment.AUDIT_CACHE_VERSION }}
      - store_test_results:
          path: unit_test_results.xml

  prepare-release:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Create draft github release
          command: ./gh-deploy.sh --draft --release --branch develop

  build-release-x86_64-linux-gnu:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Calculate cargo dependencies
          command: cargo generate-lockfile
      - restore_cache:
          key: cargo-registry-key-{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: ./build-and-package.sh --release --target x86_64-unknown-linux-gnu
      - persist_to_workspace:
          root: .
          paths: artifacts
      - store_artifacts:
          path: ./artifacts

  upload-release-artifacts:
    executor: yamp-docker-img
    steps:
      - attach_workspace:
           at: .
      - run:
          command: ls -al .
      - run:
          name: Upload to release
          command: ./gh-deploy.sh --branch develop --artifacts ./artifacts

workflows:
  develop:
    jobs:
      - test-check-profile:
          post-steps:
            - codecov/upload:
                file: profile-data/lcov.info
      - build-release-x86_64-linux-gnu:
          requires:
            - test-check-profile

  deploy:
    jobs:
      - release-approval:
          type: approval
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

      - prepare-release:
          context:
            - GITHUB_CREDS
          requires:
            - release-approval
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

      - build-release-x86_64-linux-gnu:
          requires:
            - prepare-release
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
      
      - upload-release-artifacts:
          context:
            - GITHUB_CREDS
          requires:
            - build-release-x86_64-linux-gnu
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/