version: 2.1

jobs:
  build:
    docker:
      - image: banucalin/yamp:0.0.0
        auth:
            username: banucalin
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-key-{{ checksum "Cargo.lock" }}
      - run: cargo build
      - save_cache:
          key: cargo-key-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/
  test:
    docker:
      - image: banucalin/yamp:0.0.0
        auth:
              username: banucalin
              password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-key-{{ checksum "Cargo.lock" }}
      - run: cargo test

workflows:
  build_and_test:
    jobs:
      - build:
          context:
              - build-env-vars
              - docker-hub-creds
      - test:
          requires:
            - build