version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5

executors:
  yamp-docker-img:
    docker:
      - image: banucalin/yamp:latest

jobs:
  build-debug:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-debug-key-{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-debug-key-{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}

  build-release-x86_64-linux-gnu:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Build all targets
          command: ./build-and-package.sh --release --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: ./artifacts

  test-and-profile:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Generate profile data
          command: ./profile.sh --test --tool grcov --format lcov --output profile-data
      - run: 
          name: Generate unit test xml
          command: cargo +nightly test -- -Z unstable-options --format json --report-time | cargo2junit > unit_test_results.xml
      - store_test_results:
          path: unit_test_results.xml

  format:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Formatting
          command: cargo fmt --all -- --check

  lint:
    executor: yamp-docker-img
    steps:
      - checkout
      - run:
          name: Linting
          command: cargo clippy --no-deps

  security:
    executor: yamp-docker-img
    steps:
      - checkout
      - restore_cache:
          key: cargo-audit-key-{{ .Environment.AUDIT_CACHE_VERSION }}
      - run:
          name: Check for known security issues in dependencies
          command: cargo audit || true
      - save_cache:
          paths: /usr/local/cargo/advisory-db
          key: cargo-audit-key-{{ .Environment.AUDIT_CACHE_VERSION }}

workflows:
  build-and-test:
    jobs:
      - test-and-profile:
          post-steps:
            - codecov/upload:
                file: profile-data/lcov.info
      - build-release-x86_64-linux-gnu:
          requires:
            - test-and-profile

  misc:
    jobs:
      - lint
      - format
      - security